-- Recent chats (sidebar "Recents") — persists each Chat conversation as one
-- row with its full message thread in `messages` (jsonb), matching the
-- Message[] shape ChatPage already keeps in local state. Run manually in
-- the Supabase SQL editor. NOT applied automatically and NOT executed
-- against any live database by the agent that wrote it.
--
-- Same RLS convention as every other table in this project (transactions,
-- debts, invoices, ...): `using (true)`, scoped client-side by anon_id
-- (see src/lib/anonId.ts) since there is no real Supabase auth yet.

create table conversations (
  id uuid primary key default gen_random_uuid(),
  anon_id text not null,
  -- Short label for the Recents list — the first user message, truncated.
  -- Never auto-generated by a model; plain string slicing only.
  title text not null,
  messages jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index conversations_anon_id_idx on conversations (anon_id);
create index conversations_updated_at_idx on conversations (updated_at desc);
create index conversations_deleted_at_idx on conversations (deleted_at) where deleted_at is not null;

alter table conversations enable row level security;

create policy "Allow anon read" on conversations for select using (true);
create policy "Allow anon insert" on conversations for insert with check (true);
create policy "Allow anon update" on conversations for update using (true);
